name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  release:

env:
  PYTHON_VERSION: 3.10.6
  POETRY_VERSION: 1.2.0
  NODE_VERSION: 18.8.0
  NODE_ENV: production

jobs:
  build:
    name: Test, lint, and build everything.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: web/package-lock.json
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-0
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build web site
        working-directory: web
        run: |
          npm ci
          npm run build
      - name: Lint and test Python code
        run: |
          poetry install
          poetry run black . --check
          poetry run mypy .
          poetry run ruff .
